# 显示控制，通过布尔值开关标签与 GitHub 图标
show_tags: false
show_github: false

keywords: DavidChan,imchenway
author: DavidChan,imchenway@gmail.com
description: I hear and I forget. <br>I see and I remember. <br>I write and I understand.
avatar: /source/images/favicon.png
favicon: /source/images/favicon.png

# Social Accounts
# 整个url
github: https://github.com/imchenway
mail: mailto:imchenway@gmail.com
twitter:
rss: /atom.xml
weibo:
instagram:
facebook:
wechat: https://hypha-mall.oss-cn-hangzhou.aliyuncs.com/imchenway-wechat.jpg

# 评论
duoshuo:
disqus:
gentie:

# Valine comments : https://valine.js.org
valine:
  enable: false # if you want use valine, please set enable: true
  appid:  # your leancloud appid
  appkey:  # your leancloud appkey
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: false # true/false:verify code
  avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: Just go go # comment box placeholder
